### ISSUE TITLE
Import default theme to make it work

### ISSUE THREAD

**Issue by DaveDavenport** [rose-pine/rofi#1]
Adding:

```css
@import "default"
```
at the top of the themes will make it work with "recent" rofi versions (1.7.0 and up).
 Without this the theme is incomplete and will throw undefined errors.

**Comment by mvllow** [comment]
Added in #2 – do you know if this would break versions less than 1.7.0?

**Comment by navi-desu** [comment]
The `@import "default"` can't have a `;` at the end, it was throwing errors on my end, fixed by removing the `;`. #2 was broken for me.

**Comment by mvllow** [comment]
Thanks for letting me know, removed the semicolon in #3 :)
